---
- name: Deadsnakes PPA to get Python 3.6
  become: yes
  apt_repository:
    repo: 'ppa:deadsnakes/ppa'

- name: make sure required packages are installed
  become: yes
  apt: 
    pkg: '{{ provision_packages }}'
    state: present

- name: allow long hostnames in nginx
  become: yes
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: '(\s+)#? ?server_names_hash_bucket_size'
    backrefs: yes
    line: '\1server_names_hash_bucket_size 64;'

- name: add nginx config to sites-available
  become: yes
  template: 
    src: ./nginx.conf.j2 
    dest: '/etc/nginx/sites-available/{{ project_name }}'
  notify:
      - restart nginx

- name: add symlink in nginx sites-enabled
  become: yes
  file:
      src: '/etc/nginx/sites-available/{{ project_name }}'
      dest: '/etc/nginx/sites-enabled/{{ project_name }}'
      state: link
  notify:
      - restart nginx

- name: write gunicorn service script
  become: yes
  template:
      src: ./gunicorn.service.j2
      dest: '/etc/systemd/system/gunicorn-{{ project_name }}.service'
  notify:
      - restart gunicorn
