---
# TODO: Maybe put a changed_when because it always shows changed.
# TODO: "become" is badly used, should be task by task

- hosts: development
  vars:
      host: "{{ inventory_hostname }}"
  roles:
    - provision-projects-ssh-keys
    - deploy-functional-test-tools
    - deploy-xserver-for-development-machine
    - provision-superlists
