---
# TODO: Maybe put a changed_when because it always shows changed.

- hosts: development
  vars:
      host: "{{ inventory_hostname }}"
  roles:
    - deploy-xserver-for-development-machine
    - provision-projects-ssh-keys
    # If you don't want more than one project per machine just put the project name
    # to the url of the project
    - role: provision-tdd_django_ottg
      project_port: 50776
      project_ssh_port: 2222
      project_name: localhost
      repository: git@github.com:civilian/tdd_django_ottg.git
    - role: deploy-tdd_django_ottg
      project_name: localhost
      repository: git@github.com:civilian/tdd_django_ottg.git

- hosts: development
  vars:
      host: "{{ inventory_hostname }}"
  roles:
    - deploy-functional-test-tools
    - role: deploy-tdd_django_ottg-to-run-tests
      project_name: localhost
