---
# TODO: Maybe put a changed_when because it always shows changed.

- hosts: development
  vars:
      host: "{{ inventory_hostname }}"
  roles:
    - deploy-xserver-for-development-machine
    - provision-projects-ssh-keys
    - provision-tdd_django_ottg
    - deploy-tdd_django_ottg

- hosts: development
  vars:
      host: "{{ inventory_hostname }}"
  roles:
    - deploy-functional-test-tools
    - deploy-tdd_django_ottg-to-run-tests
