# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = 'ubuntu/bionic64'

    tdd_django_ottg = 50776
    config.vm.network "forwarded_port", guest: tdd_django_ottg, host: tdd_django_ottg

    config.vm.hostname = 'guest'

    config.vm.synced_folder "../", "/vagrant"

    config.vm.provider :virtualbox do |vb|
       vb.gui = true
    end

    config.vm.provision 'shell', inline: <<-SHELL
         sudo apt-get --assume-yes install python
    SHELL

    config.vm.provision 'ansible' do |ansible|

        ansible.limit = 'development'
        ansible.inventory_path = 'provision.and.deploy.ansible/hosts'

        ansible.playbook = 'provision.and.deploy.ansible/site.yml'

        # Debug
        #ansible.verbose = 'vvvv'

    end

end
